name: Run Selenium Tests on EC2

on:
  workflow_dispatch:

jobs:
  run-on-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Launch EC2 and run script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/PicMeWebAutomation
            git pull
            chmod +x run.sh
            ./run.sh
